### ISSUE TITLE
Mac OS build, help needed.

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [facebook/folly#1038]
Hi.

Trying to build folly on Mac OS. I would like to contribute, so I need to be able to build tests and benchmarks - I cannot just take the brew installation.

bootstrap-osx-homebrew.sh fails with "autoreconf: 'configure.ac' or 'configure.in' is required"
I googled - seems like running it is no longer relevant.

CMAKE fails due to not being able to find dependencies:
```
-- Could NOT find DOUBLE_CONVERSION (missing: DOUBLE_CONVERSION_LIBRARY DOUBLE_CONVERSION_INCLUDE_DIR) 
-- Using third-party bundled double-conversion
-- Could NOT find LIBGFLAGS (missing: LIBGFLAGS_LIBRARY LIBGFLAGS_INCLUDE_DIR) 
-- Could NOT find LIBGLOG (missing: LIBGLOG_LIBRARY LIBGLOG_INCLUDE_DIR) 
-- Found libevent: /usr/local/lib/libevent.dylib
-- Found OpenSSL: /usr/lib/libcrypto.dylib (found version "1.0.2p") 
-- Looking for ASN1_TIME_diff
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBGFLAGS_INCLUDE_DIR
   used as include directory in directory /space/folly/_build/CMakeFiles/CMakeTmp
   used as include directory in directory /space/folly/_build/CMakeFiles/CMakeTmp
   used as include directory in directory /space/folly/_build/CMakeFiles/CMakeTmp
LIBGFLAGS_LIBRARY
    linked by target "cmTC_e2f29" in directory /space/folly/_build/CMakeFiles/CMakeTmp

CMake Error at /usr/local/Cellar/cmake/3.11.4/share/cmake/Modules/CheckFunctionExists.cmake:72 (try_compile):
  Failed to configure test project build system.
Call Stack (most recent call first):
  CMake/folly-deps.cmake:75 (check_function_exists)
  CMakeLists.txt:85 (include)


-- Configuring incomplete, errors occurred!
```

Could you please give instructions on how to build folly: from clear download to running tests and benchmarks?

**Comment by JoeLoser** [comment]
I have a PR that I'll submit shortly which will fix this script to work with the CMake builds. When the build system switched from Autotools to CMake several months ago, this script, unfortunately, was not updated. Stay tuned and I'll throw up a PR tonight.

**Comment by DenisYaroshevskiy** [comment]
Hi.

Thank you for doing this.
With this pr I still get an error:

```
-- Boost version: 1.68.0
-- Found the following Boost libraries:
--   context
--   chrono
--   date_time
--   filesystem
--   program_options
--   regex
--   system
--   thread
--   atomic
-- Could NOT find DOUBLE_CONVERSION (missing: DOUBLE_CONVERSION_LIBRARY DOUBLE_CONVERSION_INCLUDE_DIR) 
-- Using third-party bundled double-conversion
-- Could NOT find LIBGLOG (missing: LIBGLOG_LIBRARY LIBGLOG_INCLUDE_DIR) 
-- Found libevent: /usr/local/lib/libevent.dylib
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.11") 
-- Found BZip2: /usr/lib/libbz2.dylib (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - not found
-- Looking for lzma_auto_decoder in /usr/local/lib/liblzma.dylib
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBGFLAGS_LIBRARY
    linked by target "cmTC_27829" in directory /space/joeloser_folly_fork/_build/CMakeFiles/CMakeTmp

CMake Error at /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/CheckLibraryExists.cmake:56 (try_compile):
  Failed to configure test project build system.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/FindLibLZMA.cmake:46 (CHECK_LIBRARY_EXISTS)
  CMake/folly-deps.cmake:91 (find_package)
  CMakeLists.txt:85 (include)


-- Configuring incomplete, errors occurred!
See also "/space/joeloser_folly_fork/_build/CMakeFiles/CMakeOutput.log".
See also "/space/joeloser_folly_fork/_build/CMakeFiles/CMakeError.log".
```

Here is what I did:
```
./build/bootstrap-osx-homebrew.sh
cd ../
mkdir _build
cd _build/
cmake ..
```

**Comment by JoeLoser** [comment]
I see a few errors so far:

1. It seems `LIBGFLAGS_LIBRARY` is not getting set for you in https://github.com/facebook/folly/blob/master/CMake/FindGFlags.cmake

- I just pushed up a commit to explicitly specify the lib path: https://github.com/JoeLoser/folly/commit/948b94a327054739daac4a24b3b996b21ba38311#diff-77814eed1479228924c6fe0717f50bc8R53

2. It looks like LZMA is not properly getting found for you. LZMA is also known as `xz`, which we specify in the bootstrap script to get installed (https://github.com/JoeLoser/folly/commit/a2279f622b0660e85fc422e707cd9b79909bdb76#diff-77814eed1479228924c6fe0717f50bc8R31). I am not sure why this is failing for you. It should not require running `brew link xz` (to put symlinks for `/usr/local/bin/xz`). I unlinked `xz` and the script worked fine still.

3. You will also need the commit from here: https://github.com/facebook/folly/pull/1040
otherwise, there is an error in which a CMake variable is empty resulting in a hard error for detecting system architecture on Mac OS X.


Please try removing the `_build` directory, creating a branch which contains https://github.com/JoeLoser/folly/commit/948b94a327054739daac4a24b3b996b21ba38311 and https://github.com/JoeLoser/folly/commit/39acc42895a61c4c4ec30823b807682a2bbb9a04 and report back what other errors (if any) you have and we can go from there.

**Comment by DenisYaroshevskiy** [comment]
I'm not sure I got all of that.
I cleaned everything
Checked out latest version of bootstrap_osx
Cherry-picked this commit: https://github.com/JoeLoser/folly/commit/39acc42895a61c4c4ec30823b807682a2bbb9a04

This is what Cmake produced as a result:
```
Deniss-MacBook-Air:folly denisarosevskij$ ./build/bootstrap-osx-homebrew.sh 
+ set -e
+++ dirname -- ./build/bootstrap-osx-homebrew.sh
++ cd ./build/..
++ pwd
+ BASE_DIR=/space/joeloser_folly_fork/folly
+ cd /space/joeloser_folly_fork/folly
+ cd ..
+ mkdir -p _build
+ cd _build
++ brew --prefix openssl
+ OPENSSL_INCLUDES=/usr/local/opt/openssl/include
++ brew --prefix gflags
+ GFLAGS_ROOT=/usr/local/opt/gflags
+ GFLAGS_INCLUDES=/usr/local/opt/gflags/include
+ GFLAGS_LIB=/usr/local/opt/gflags/lib
+ cmake -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include -DLIBGFLAGS_INCLUDE_DIR=/usr/local/opt/gflags/include -DLIBGFLAGS_LIBRARY=/usr/local/opt/gflags/lib ..
-- The CXX compiler identification is AppleClang 10.0.0.10001044
-- The C compiler identification is AppleClang 10.0.0.10001044
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Boost version: 1.68.0
-- Found the following Boost libraries:
--   context
--   chrono
--   date_time
--   filesystem
--   program_options
--   regex
--   system
--   thread
--   atomic
-- Could NOT find DOUBLE_CONVERSION (missing: DOUBLE_CONVERSION_LIBRARY DOUBLE_CONVERSION_INCLUDE_DIR) 
-- Using third-party bundled double-conversion
-- Could NOT find LIBGLOG (missing: LIBGLOG_LIBRARY LIBGLOG_INCLUDE_DIR) 
-- Found libevent: /usr/local/lib/libevent.dylib
-- Found OpenSSL: /usr/lib/libcrypto.dylib (found version "1.0.2q")  
-- Looking for ASN1_TIME_diff
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBGFLAGS_LIBRARY
    linked by target "cmTC_5dc44" in directory /space/joeloser_folly_fork/_build/CMakeFiles/CMakeTmp

CMake Error at /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/CheckFunctionExists.cmake:72 (try_compile):
  Failed to configure test project build system.
Call Stack (most recent call first):
  CMake/folly-deps.cmake:75 (check_function_exists)
  CMakeLists.txt:85 (include)


-- Configuring incomplete, errors occurred!
See also "/space/joeloser_folly_fork/_build/CMakeFiles/CMakeOutput.log".
```

Contains output: https://gist.github.com/DenisYaroshevskiy/c870e196ce4e0b7cd41281d74e27757e

**Comment by JoeLoser** [comment]
Can you show the output from `brew --prefix gflags`? If you do have gflags installed, is it brew linked? It should not be required for building folly.  

Does adding `-DCMAKE_LIBRARY_PATH=/usr/local/Cellar` to the cmake invocation help? You can specify alternate search paths for include directories/libs as a whole to `cmake` via

`-DCMAKE_LIBRARY_PATH=<path>` and `-DCMAKE_INCLUDE_PATH=<path>` (as seen from https://github.com/facebook/folly/blob/master/README.md)

**Comment by DenisYaroshevskiy** [comment]
gflags:
```
Deniss-MacBook-Air:_build denisarosevskij$ brew --prefix gflags
/usr/local/opt/gflags
```
I added ` -DCMAKE_LIBRARY_PATH=/usr/local/Cellar \` and then  replaced it with:`DCMAKE_LIBRARY_PATH=/usr/local/opt \
` to cmake invocation in `folly/build/bootstrap-osx-homebrew.sh` but none of them seem to help.

Sorry - building is more or less dark magic for me.

**Comment by JoeLoser** [comment]
Does brew linking all of the dependencies help? For example, something like:

```
brew link \
    boost \
    double-conversion \
    gflags \
    glog \
    libevent \
    lz4 \
    snappy \
    xz \
    libsodium
```

**Comment by DenisYaroshevskiy** [comment]
Had to run 'brew install libsodium'
After that I get:
```
Deniss-MacBook-Air:joeloser_folly_fork denisarosevskij$ brew link \
>     boost \
>     double-conversion \
>     gflags \
>     glog \
>     libevent \
>     lz4 \
>     snappy \
>     xz \
>     libsodium
Warning: Already linked: /usr/local/Cellar/boost/1.68.0_1
To relink: brew unlink boost && brew link boost
Linking /usr/local/Cellar/double-conversion/3.1.1... 
Error: Could not symlink lib/cmake/double-conversion
/usr/local/lib/cmake is not writable.
```

I'm happy to do a skype session, so that debugging this is less tidious.

**Comment by DenisYaroshevskiy** [comment]
Found out that I was suffering from: https://github.com/Homebrew/brew/issues/3228

Next error:
```
CMake` Error in CMakeLists.txt:
  Target "folly_deps" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/space/joeloser_folly_fork/DOUBLE_CONVERSION_INCLUDE_DIR-NOTFOUND"

  which is prefixed in the source directory.
```

**Comment by DenisYaroshevskiy** [comment]
Ok, brew link double-conversion helped with that.
Now folly doesn't build. Some jmalloc issue.

https://gist.github.com/DenisYaroshevskiy/8d4bf74d28eba7429715d1159ad36064

**Comment by DenisYaroshevskiy** [comment]
Ok, turns out it's this issue: https://github.com/facebook/folly/issues/652
only in reverse, this the patch that made it work:

```
-CHECK_INCLUDE_FILE_CXX(jemalloc/jemalloc.h FOLLY_USE_JEMALLOC)
+# CHECK_INCLUDE_FILE_CXX(jemalloc/jemalloc.h FOLLY_USE_JEMALLOC)
```

If I remove this line: https://github.com/facebook/folly/blob/7a5aa125f9ccb5f84911c982a06990e47d82fb88/CMake/FollyConfigChecks.cmake#L9

`./build/bootstrap-osx-homebrew.sh` finishes successfully.

Thanks for the help.

Remaining questions:

- Will you merge your patch? It was the first obstacle and I would prefer to work with the original repo and not your fork.
- Can JMALOC problem be solved as part of the bootstrap?
- Can you please tell me how to build/run tests?
- And how to build/run benchmarks?

I do see the source files but I don't see simple one liner and it doesn't seem to be a very simple  exercise to extract this information from CMAKE.

**Comment by JoeLoser** [comment]
Glad you're making good progress.

Seems like #652 is worth getting to the bottom of for those with `jemalloc` installed on Mac OS X, but it's not strictly required for this work.

Arguably, the `bootstrap-osx-homebrew.sh` script could run `brew link` for each of the dependencies installed via `homebrew` to avoid user surprises when they need to possibly run `brew link`.  Even though this is a reversible process by the user (via `brew unlink`), I didn't love adding that to the script; not to mention it is a change in behavior which I would want to come in a different commit/PR than this.

To your questions:

-  My patch has been imported internally into Facebook's diff tool where others will review it. I imagine https://github.com/facebook/folly/pull/1041 will land soon. Maybe @calebmarchent, if you have some time, can you please give a review? I've seen you do some build-related work as of late. Thanks in advance.
- I don't think the `jemalloc` duplicate symbol issue is at all related to this commit/PR. It is a separate problem and should be addressed as such. Sounds like a good place for your first folly PR if you are interested.
- As for the tests, to the cmake invocation, you need to pass `-DBUILD_TESTS=ON`. I did not choose to build tests by default for those running this bootstrap script to prevent any change in behavior. This commit was purely targeted as using `cmake` instead of `autotools`.

**Comment by DenisYaroshevskiy** [comment]
Seems like GMOK is missing from dependencies

CMake Error at /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find GMock (missing: LIBGMOCK_MAIN_LIBRARY LIBGMOCK_LIBRARY
  LIBGTEST_LIBRARY LIBGMOCK_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  CMake/FindGMock.cmake:48 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:358 (find_package)

**Comment by JoeLoser** [comment]
`GMock` is only required if you are building the tests as seen at https://github.com/facebook/folly/blob/master/CMakeLists.txt#L358. Since this script does not build the tests by default, `GMock` is currently not installed by this script.

Do you think we should instead install the dependencies needed for building the tests, even though the default is to not build the tests with this script? One argument for not doing that is you are not installing the minimum set of dependencies needed to accomplish what the user asked for (build folly, not build/run tests).

What do you think @calebmarchent?

**Comment by DenisYaroshevskiy** [comment]
I think that the task of 'I want to build the library + benchmarks and tests' should be relatively straigthforward.

Right now it's not: you can't just do cmake -DBUILD_TEST ../ - you have to go and patch the script to do that.

I would love a command line option to sh script, smth like 'developer mode' that would also prepare everything for developing.

BTW: does folly use fuzzing?

**Comment by JoeLoser** [comment]
In my opinion, a `bootstrap`-like script is meant to be run once. If someone is actively doing development on folly, I imagine they just run `cmake` themselves to avoid the time it takes to check the dependencies with `homebrew` every time cmake is re-run.

Would you prefer an option to the bash script for running tests? If this option is defined, it could install the extra dependencies and also pass the correct CMake option through to build the tests. 

I am not sure whether folly uses fuzzing for testing inputs. I would lean on @yfeldblum or @Orvid to answer this.

**Comment by DenisYaroshevskiy** [comment]
Maybe not running, just building?
The problem with CMAKE - it's not obvious how to run CMAKE.
You have at least 3 flags that are passed in the brew script, probably for debug/release would be more.

I don't know how to best organise this process, but I think it would be great if a person could modify code, add a test or a benchmark without diving in to the depth of build scripts.

**Comment by DenisYaroshevskiy** [comment]
I have zero experience with docker - but maybe this is the solution?  Like 'folly developer docker container'?

**Comment by calebmarchent** [comment]
We may need to consider adding a TravisCI job for MacOS; to ensure the MacOS build stays working once the present issues are resolved.
