### ISSUE TITLE
How to build test case 

### ISSUE THREAD

**Issue by darionyaphet** [facebook/folly#1240]
Hi team:

I'm a beginner to learn folly and  have use `./folly/build/bootstrap-osx-homebrew.sh` to build `folly` on `Mac`. I want to build out some test case in order to learn some case. 

But I don't find it. thanks 👍

**Comment by JoeLoser** [comment]
The CMake option you are looking for is `BUILD_TESTS`, which defaults to `OFF`. Since the `bootstrap-osx-homebrew.sh` script allows users to pass their own option to cmake in [as seen here](https://github.com/facebook/folly/blob/master/folly/build/bootstrap-osx-homebrew.sh#L66), you can just pass `-DBUILD_TESTS=ON` to the script.

I'll put a PR out to mention this CMake option in the `README`.
