### ISSUE TITLE
Get rid of fbstring?

### ISSUE THREAD

**Issue by tudor** [facebook/folly#1253]
Hey @yfeldblum -- when I was still at FB, there was talk of getting rid of fbstring, given that libstdc++ (and presumably libc++ as well?) has long used the small-string optimization for std::string.

Is that still being worked on?

**Comment by afrind** [comment]
proxygen still uses fbstring for a particular use-case where the smaller size (24 vs 32 bytes) makes a noticeable difference.

**Comment by yfeldblum** [comment]
Hey @tudor, we are not removing `fbstring` from folly and I don't recall any talk that we would. We no longer patch it into libstdc++ now that libstdc++ ships an implementation with in-situ storage, which is what I think might have been the historical discussion. But since there are numerous cases which use `fbstring` explicitly by name (v.s. using it implicitly by naming `std::string` and getting `fbstring`'s implementation) and which presumably get better results from using it, it's staying. It has larger in-situ storage (24 bytes), it is relocatable, and it is condition-free move-constructible, which are advantages `fbstring` has over libstdc++ `std::string` that various use-cases may rely on.
