### ISSUE TITLE
[QUESTION] Does the F14 hash table supersede the AtomicHashMap?

### ISSUE THREAD

**Issue by jrhemstad** [facebook/folly#1380]
Is the newer [F14 Hash Table](https://github.com/facebook/folly/blob/master/folly/container/F14.md) considered to be strictly superior to the older [AtomicHashMap](https://github.com/facebook/folly/blob/master/folly/docs/AtomicHashMap.md)? 

Or are there still cases where I would prefer one over the other?

**Comment by yfeldblum** [comment]
`F14NodeMap` is a superior version of `std::unordered_map`. Unfortunately, the standard and the standard library implementations tend to be constrained from improving their data structures, such as the ones in `std::unordered_map`, since changes to data structures tend to be ABI breaks. Therefore, it is up to the rest of us to write improved data structures when the ones in the standard library are insufficiently performant.

`F14ValueMap` and `F14VectorMap` are different unordered-map implementations offering different semantics. Typically, they offer fewer guarantees about reference stability in exchange for improved performance and improved heap usage, as compared with `F14NodeMap`.

None is a replacement for `AtomicHashMap`, since none is a concurrent data structure like `AtomicHashMap`.
