### ISSUE TITLE
Promise::detach seems calling wrong detach function of Core

### ISSUE THREAD

**Issue by lijunsong** [facebook/folly#1381]
When Promise's destructor is called, it calls `detach` and `detach` calls `core_->detachFuture`, not `core_->detachPromise`.
```
template <class T>
Promise<T>::~Promise() {
  detach();
}

template <class T>
void Promise<T>::detach() {
  if (core_) {
    if (!retrieved_) {
      core_->detachFuture();
    }
    futures::detail::coreDetachPromiseMaybeWithResult(*core_);
    core_ = nullptr;
  }
}
```

Logically there are no differences but `detachPromise` also checks result

```
  /// Called by a destructing Future (in the consumer thread, by definition).
  /// Calls `delete this` if there are no more references to `this`
  /// (including if `detachPromise()` is called previously or concurrently).
  void detachFuture() noexcept {
    detachOne();
  }

  /// Called by a destructing Promise (in the producer thread, by definition).
  /// Calls `delete this` if there are no more references to `this`
  /// (including if `detachFuture()` is called previously or concurrently).
  void detachPromise() noexcept {
    DCHECK(hasResult());
    detachOne();
  }
```

**Comment by mpark** [comment]
Typically, a `Future` side would be retrieved from the `Promise` and the `Future` would invoke `detachFuture`. However, if a `Future` is not retrieved from the `Promise` at all, there's no `Future` present to invoke the `detachFuture`. In such a case (`!retrieved`), we call `detachFuture` from the `Promise` side. This is a result of initializing `Core` with 2 attached, rather than incrementing by 1 at the time when a `Future` is retrieved. Additionally, the `coreDetachPromiseMaybeWithResult` function ultimately invokes `detachPromise`.
