### ISSUE TITLE
Add a target to cmake to create a folly  RPM for RedHat based Linux distributions

### ISSUE THREAD

**Issue by martind1111** [facebook/folly#1384]
It would be very convenient to be able to generate an RPM for RedHat based Linux distribution from the git repo. We could provide a package target in cmake to package an RPM based on the artifacts that are created during the build process. CPack could be used to help in the process.

**Comment by yfeldblum** [comment]
Keep in mind that there is no stable folly abi and that every folly commit may be presumed to be abi-breaking. Writing package targets may give the opposite impression. Internally, we have a monorepo with no versioning. Every internal project build uses the same-rev version of folly from the same rev in the monorepo, which avoids any problems that normally arise from unstable abi's.

**Comment by roligugus** [comment]
We're in a similar boat as @martind1111 . While I personally would love to use a monorepo, we cannot at our company. So we periodically take snapshots, build rpms using custom spec files and then our different products depend on that.
This could possibly help.

The tricky part is the versioning of the rpms due to potential ABI breakage as you mention. The PACKAGE_VERSION has not been updated the last few years. Afaik, we're creating a unique version every time we update or we use the tags as a base - cannot remember exactly. Since we're not updating "too often" that approach works for us.
