### ISSUE TITLE
Is it correct for the line MPMCQueue.h#L1496 

### ISSUE THREAD

**Issue by dangleptr** [facebook/folly#1475]
https://github.com/facebook/folly/blob/1902d0ffbac59232885f7b4797b24058d4a336b6/folly/MPMCQueue.h#L1496

Why not `new (&contents) T()` ?

**Comment by nbronson** [comment]
The code is as intended, but obsolete. Facebook C++ code pre-dates C++11's rvalues and noexcept move constructors. As an optimization to avoid copies, some types were marked "relocatable", which meant that they had no internal pointers and could be moved from one place in memory to another with memcpy. This was an important optimization for fbvector<fbstring>, for example.

The code path you are looking at was written after C++11, but while some types at Facebook had not yet been updated. It emulates move-constructing a new object at &contents_ from std::move(goner), for legacy types that are relocatable but not noexcept moveable. After a modern move construction there should be two objects, one of which is empty. The memcpy "relocates" the object from goner to contents_, but leaves only one live object. The line you are looking at creates a new empty object in its place. This code certainly falls afoul of the standard and is unnecessary for modern types, but it was useful at the time.

Note that the relocatable property is less restrictive than std::is_trivial, because the class can still own memory so long as it doesn't have internal pointers. std::unique_ptr is relocatable, for example.

**Comment by dangleptr** [comment]
>>> After a modern move construction there should be two objects, one of which is empty. The memcpy "relocates" the object from goner to contents_, but leaves only one live object. The line you are looking at creates a new empty object in its place. 

Got it.  Thanks for your explanation.  @nbronson
