### ISSUE TITLE
ThreadPoolExecutor: How to know whether one of the workers threw an exception?

### ISSUE THREAD

**Issue by adshastri** [facebook/folly#1763]
It seems that exceptions are caught and swallowed for a thread pool executor: https://github.com/facebook/folly/blob/53637452d07ff8c24a77d3f5f73bbe79af501ba3/folly/executors/ThreadPoolExecutor.cpp#L133. 

When I call `join` on the executor, is there a way to know whether a thread has failed and bubble up the exception?

**Comment by yfeldblum** [comment]
Thanks for the idea, but this does not look like something we could do.

Collecting errors is not really something that thread pool executors or other executors would provide. Although it is possible to have your own executor adaptor that provides it.

In part, the async frameworks already collect errors and do not let them escape to the executors. For example, the `Future` you get from async work holds onto any error that the corresponding promise completes with. Likewise for `Task`. So this concern applies only when using executors directly, and not when using them as part of an async framework.

We log errors because not all async work is done using async frameworks, and we would like to do something that makes these errors visible in some way and that does not merely abort the process. In comparison to thread functions which raise errors rather than returning, in which case the threads abort the process.

In part, the only reasonable implementation would be first-error, which can be performant but which cannot provide any sort of continuous or current information. Last-error would require an additional synchronization on every error, which we would want to avoid. And all-errors would require unbounded memory use in addition to additional synchronization on every error, and we want to avoid unbounded memory use as well.
