### ISSUE TITLE
Build error in folly on Ubuntu 20.04

### ISSUE THREAD

**Issue by pyelaman** [facebook/folly#1791]
Build failed while building memcpy.S due to "unrecognized command line option '-fcoroutines'".

Not sure which version of "cc" compiler supports it.

**Comment by Orvid** [comment]
Compiling with the C++ compiler rather than the C compiler should be enough to get it working for now. I have a change up internally to make sure that `-fcoroutines` is only passed to the C++ compiler, not the assembly preprocessor.

For now, changing https://github.com/facebook/folly/blob/main/CMakeLists.txt#L220 to:
```
add_compile_options($<$<COMPILE_LANGUAGE:CXX>:-fcoroutines>)
```
Should fix it.
