### ISSUE TITLE
Should we ever use CPUThreadPoolExecutor with a blocking queue?

### ISSUE THREAD

**Issue by baiyanhuang** [facebook/folly#1864]
The [comment in code](https://github.com/facebook/folly/blob/main/folly/executors/CPUThreadPoolExecutor.h#L47) says: 

>  * @note If a blocking queue (folly::QueueBehaviorIfFull::BLOCK) is used, and
>  * tasks executing on a given thread pool schedule more tasks, deadlock is
>  * possible if the queue becomes full.  Deadlock is also possible if there is
>  * a circular dependency among multiple thread pools with blocking queues.
>  * To avoid this situation, use non-blocking queue(s), or schedule tasks only
>  * from threads not belonging to the given thread pool(s), or use
>  * folly::IOThreadPoolExecutor.

Does it mean there is bug/limitation for  CPUThreadPoolExecutor to work with a blocking queue?  
I am currently using CPUThreadPoolExecutor with below blocking queue:
```
folly::LifoSemMPMCQueue<folly::CPUThreadPoolExecutor::CPUTask, folly::QueueBehaviorIfFull::BLOCK>;
```

I am buildig a pipeline with a lot of CPUThreadPoolExecutor with blocking queue, for the purpose so the whole pipeline could be throttled when there resouce is exhausted, but I did came across deadlocks even I `schedule tasks only from threads not belonging to the given thread pool(s)`

Should I use CPUThreadPoolExecutor with a non-blocking queue, and then use a separated queue myself to do the throttling?

**Comment by yfeldblum** [comment]
This is just the nature of a bounded queue.

Folly's futures, fibers, and coroutines frameworks will not work well when used with executors that have bounded queues that either block or fail at enqueue when full.

One alternative is to use async semaphores more explicitly in your application code around access to resources, and even to track these semaphores so that admission at the service boundary can be throttled and create backpressure.
