### ISSUE TITLE
folly/stats/*-defs.h not included in parent classes

### ISSUE THREAD

**Issue by senior7515** [facebook/folly#191]
# If you don't include the -def.h companion header when including any of the stats packages, there are missing symbols

* Example:

Trying to compile a program with this: 

```
#include <folly/stats/Histogram.h>
// -- missing -- #include <folly/stats/Histogram-defs.h>
```

Generates this error: 

```
/usr/local/include/folly/stats/Histogram.h:231: undefined reference to `folly::detail::HistogramBuckets<unsigned long, folly::detail::Bucket<unsigned long> >::HistogramBuckets(unsigned long, unsigned long, unsigned long, folly::detail::Bucket<unsigned long> const&)'
```

The fix is simple: 

```
#include <folly/stats/Histogram.h>
#include <folly/stats/Histogram-defs.h>
```

# Happy to contribute this to all the folly/stats/* classes, but wanted to confirm. 

I noticed that for all template deps that were broken into different headers the idiom is to use the

```
 <class_name>-inl.h  

// example:

#ifndef FOLLY_URI_H_
#error This file may only be included from folly/Uri.h
#endif

```

Thoughts?

**Comment by Gownta** [comment]
Good eye! There are two different idioms at play here.

One is a readability idiom: break out the definitions from the declarations, so that the main header is easier to read. For these files, we include the -inl from the bottom of the main .h.

The second is a compiler idiom: break out the definitions from the declarations, because most people don't want to include the definitions (which are templated) since they go unused. Especially since the definitions are in a header, this saves a significant amount of template bloating. For people who actually need the definitions, the include the -def file from the source file that actually requires them.

In both cases, the -inl/-def file should only be included after its associated header has been included.

This particular case is the latter. So we actively want these headers separated.
