### ISSUE TITLE
How to compile and run test.cpp?

### ISSUE THREAD

**Issue by nhattanmai** [facebook/folly#204]
Here's an example:

    #include <folly/Benchmark.h>
    #include <folly/Foreach.h>
    #include <vector>
    using namespace std;
    using namespace folly;
    BENCHMARK(insertFrontVector) {
      // Let's insert 100 elements at the front of a vector
      vector<int> v;
      FOR_EACH_RANGE (i, 0, 100) {
        v.insert(v.begin(), i);
      }
    }
    BENCHMARK(insertBackVector) {
      // Let's insert 100 elements at the back of a vector
      vector<int> v;
      FOR_EACH_RANGE (i, 0, 100) {
        v.insert(v.end(), i);
      }
    }
    int main() {
      runBenchmarks();
    }

Please tell me way to compile and run test.cpp? Thanks :)

**Comment by bowlofstew** [comment]
This "issue" probably belongs in the Google Group, https://groups.google.com/d/forum/facebook-folly, instead of a Github issue but here is a rough CMake file that you should be able to tweak and use:

# create a build directory at the same level of your file
# cd build && cmake .. 
# make
# ./example
cmake_minimum_required(VERSION 3.2)
project(ProjectName)
set(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} "-std=c++11")
set(FOLLY_PATH "YOU_PATH_TO_FOLLY_INCS_GOES_HERE")
include_directories(FOLLY_PATH)
add_executable(example test.cpp)

Give it a shot and if you are still having issues, let's continue it over on Google Groups.
