### ISSUE TITLE
Question: What does * and *+ mean for a lambda?

### ISSUE THREAD

**Issue by ruiyuanlu** [facebook/folly#2157]
Hi, I tried to figure out the meaning of `*identity` and `*+identity` used in [ExceptionTest.cpp](https://github.com/facebook/folly/blob/main/folly/lang/test/ExceptionTest.cpp#L164-L165) but had no idea.  I've never seen sth like this brefore. Why are these operators used on the lambda function `identity`?

Many thx for your help.
```c++
auto identity = [](int i) { return i; };
EXPECT_EQ(3, folly::catch_exception<int>(returner(3), +identity));
EXPECT_EQ(3, folly::catch_exception<int>(returner(3), *+identity));
```

**Comment by Orvid** [comment]
@yfeldblum Any comment here?

**Comment by yfeldblum** [comment]
Every capture-free or static lambda has a built-in conversion to pointer-to-function. IIUC, the use of `+` triggers conversion because the compiler looks for any intermediate built-in conversion that would allow `+` on the converted-to type. Unary `+` of a pointer is a no-op. And `*+` is just getting a reference-to-function from pointer-to-function the way `*` normally does.

https://en.cppreference.com/w/cpp/language/lambda
https://en.cppreference.com/w/cpp/language/implicit_conversion
