### ISSUE TITLE
'cstdlib' file not found

### ISSUE THREAD

**Issue by DanielKuhn** [facebook/folly#2162]
Screenshot says it all...
![Bildschirmfoto 2024-03-13 um 17 47 53](https://github.com/facebook/folly/assets/16227674/b7b2fb34-e358-4b9e-9b1e-bfe96cad4601)

**Comment by fossejc** [comment]
@DanielKuhn I have exactly the same error when building my code. Were you able to fix the issue ? If yes how ?

**Comment by DanielKuhn** [comment]
The problem was an import in the `libffi_apple`-dependency. If you're using that, try upgrading it to a newer version or add this to your Podfile:

```
if target.name == 'libffi_apple' 
  target.build_configurations.each do |config|
    config.build_settings['HEADER_SEARCH_PATHS'] = ['$(inherited)', '$(PODS_TARGET_SRCROOT)']
    config.build_settings['USE_HEADERMAP'] = 'NO'
  end
end
```

Full discussion here:
https://github.com/623637646/SwiftHook/issues/13

**Comment by fossejc** [comment]
Hi @DanielKuhn, thank you very much for your quick answer. 

In my case the issue was different but as this Github issue was the one that kept coming on Google I will leave my solution here.

The issue was due to the fact that I had the wrong search headers when building my expo native module. When using MacOS 26, the c++ headers path that worked is `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/c++/v1`

Here is my full pod_target_xcconfig
```
s.pod_target_xcconfig = {
    'DEFINES_MODULE' => 'YES', # Ensure the module is defined
    "HEADER_SEARCH_PATHS" => "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/c++/v1",
    "CLANG_CXX_LANGUAGE_STANDARD" => "c++17",
    'CLANG_CXX_LIBRARY' => 'libc++',
    'USE_HEADERMAP' => 'NO' # Disable header maps
}
```

I hope it helps someone
