### ISSUE TITLE
NamedPipe Support

### ISSUE THREAD

**Issue by SteveSelva** [facebook/folly#2346]
Does folly support named pipes in Windows?

If not, is there any plan to support it in future?

**Comment by Orvid** [comment]
What would named pipe support look like? Where would you expect them to work?

Currently folly doesn't actually use pipes on windows in many cases because libevent doesn't support them (or at least, it didn't when I last looked 6 years ago). For the most part, we use `socketpair` instead.

https://github.com/facebook/folly/blob/main/folly/portability/Unistd.cpp#L383
