### ISSUE TITLE
Google groups banned folly. Can we make another group or fix this?

### ISSUE THREAD

**Issue by GabrielPedroza** [facebook/folly#2349]
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/373c7ca4-7619-424b-9365-90e4aef38728">

**Comment by Orvid** [comment]
I was actually not aware we still had a google group, though I have found the link. I'll take a look, but I suspect the answer we may go with is to just abandon it, unless there was significant usage that none of us were aware of?

**Comment by mszabo-wikia** [comment]
Looking at the [most recent snapshot](https://web.archive.org/web/20240304230730/https://groups.google.com/g/facebook-folly) of the group before it got banned, engagement appears to have been marginal to begin with, and there have been no new posts since 2022. Based on this, I doubt a new group would be very useful.

**Comment by GabrielPedroza** [comment]
Agreed — will close this issue now

**Comment by Orvid** [comment]
The github discussions are newly enabled as-of yesterday, and should  be used instead of the google group, even if it ever does get unbanned.
