### ISSUE TITLE
Improve the documentation so that people can see and use this really good library

### ISSUE THREAD

**Issue by atuljangra** [facebook/folly#360]
Currently the landing page of this repo doesn't say much about what this library is?
Agreed that it is a utility library, but just stating "Folly is an open source C++ library developed and used by Facebook" is bad documentation.
Maybe we should get https://github.com/facebook/folly/blob/master/folly/docs/Overview.md this out or add more documentation on the landing page. This can be brief and point to more in-depth documentation available in /docs/.

**Comment by gregstula** [comment]
+1 this reddit thread highlights the problem with the lack of good documentation

https://www.reddit.com/r/cpp/comments/43xuxv/why_dont_more_people_use_the_folly_library/

**Comment by lbrandy** [comment]
Yea. Agreed. I'm going to move a bunch over Overview.md up to the main readme and clean some of this up.

**Comment by atuljangra** [comment]
Thanks @lbrandy :+1:

**Comment by abhiguru** [comment]
+1

**Comment by Dalzhim** [comment]
Adding documentation for the IOBuf class along with efficient usage examples would help a lot in order to use the proxygen library efficiently. As an example, wrapping a std::string object within the IOBuf structure isn't very intuitive with the IOBuf interface.

**Comment by bharath-g** [comment]
Also please some documentation on building and running tests. You can make it self contained and not assume the audience does not have experience gtest. That way it will be better. If tests worked out of the box , atleast we can read the tests and figure out how things work even without documentation. 

right now after I download and build I don't know how to run a suite of tests.

**Comment by yfeldblum** [comment]
#550 adds the tests for `folly/io/` to the build.

**Comment by necro351** [comment]
As part of your documentation refactor, can you describe a step-by-step process to setup the library in Ubuntu 16? Specifically make check fails with `make[3]: *** No rule to make target 'gtest/googletest/src/gtest-all.cc', needed by 'gtest/googletest/src/libfollytestmain_la-gtest-all.lo'.  Stop.` despite installing libgtest-dev via `sudo apt-get install libgtest-dev` (which the docs also do not include in the dependencies). Since Ubuntu 16 is one of your most (most?) popular platforms for this library, I think your docs need to include instructions that work for it. Thoughts?

BTW: There are multiple unassigned issues in your issue tracker talking about this problem and adoption in the community would be stronger if people saw these sorts of basic boot-strapping issues get assigned to contributors.

**Comment by ahornby** [comment]
updated README.md, a bit late for this issue but hopefully it helps
