### ISSUE TITLE
Doesn't work along with libev

### ISSUE THREAD

**Issue by dydoser** [facebook/folly#601]
Hi! My project that using folly/fibers works when I run it on Mac OS, but it crushes on the assertion: `io/async/EventHandler.cpp:46: bool folly::EventHandler::registerImpl(uint16_t, bool): Assertion event_.ev_base != nullptr' failed` when I compile it on Ubuntu 16.04 or Debian 8. I've figured out that libev cause the problem. I've created a simple test [project](https://github.com/dydoser/fibers_libev) that runs on Debian 8 without linking with libev but cause the exception with it. On Mac Os it runs anyway. I've compiled the same versions of libev and libevent that set on Mac Os: `libev 4.24 libevent 2.1.8` and recompiled folly, but it doesn't work anyway. Could you help me?

**Comment by baranyaib90** [comment]
Hi,
I have met this problem.
The **cause** is: the integrated libevent wrapper in libev.
Easier **work around**: compile libev from source, but first remove events.c and events.h from Makefile.am.
**Explanation**:
libev library provides a built-in libevent wrapper.
This would help developers to easily replace libevent to libev with a simple re-compile :)
The crash occurs, because folly intents to use libevent library, but the shared library function calls will be mixed up with libev's wrapper functions.

I hope, this could help you, after so much time.

**Comment by dydoser** [comment]
I've replaced a library which requires libev, but anyway thanks for such a great library!

**Comment by Supremes** [comment]
I have met same question like you.Does it mean that it's enough to install libev and it will work?
