### ISSUE TITLE
support -fno-exceptions

### ISSUE THREAD

**Issue by ecnalubma** [facebook/folly#615]
Hello,

I'd like to ask the folly developers to consider supporting builds with -fno-exceptions. Some folly components do this already, but many don't. It would be nice to have this configurable at build-time, but I don't see a flag to do this.

**Comment by yfeldblum** [comment]
`folly/Optional.h` should now support `-fno-exceptions`, and maybe some other libraries, by using `folly::throw_exception` rather than `throw` statements. This is not a build-time control.

I don't expect every library will support `-fno-exceptions`, but if there are additional ones that are needed, that can be considered. Closing for now.
