### ISSUE TITLE
folly::toJson reorders object order

### ISSUE THREAD

**Issue by AdamDailyMotion** [facebook/folly#672]
I've been building a folly::dynamic object in a specific order and convert it to json using folly::toJson(). For some reason it reorders the fields which doesn't matter for my parser, but is really inconvenient when I want to look through the json manually. I know you can sort the parsed json but that not really the same thing as keeping the original order.
Is there an obvious reason for this? (perhaps I'm doing something wrong)

**Comment by suspend0** [comment]
folly json is built on folly::dynamic which uses std::unordered_map under the hood.

**Comment by yfeldblum** [comment]
Neither of the two standard library map types preserves insertion order. There was no use-case for `folly::dynamic` requiring preservation of insertion order. So, as @suspend0 notes, `folly::dynamic` just uses one of the standard library map types.

Closing, because this answers the original question as asked.
