### ISSUE TITLE
Get this error while executing "cmake configure .." command

### ISSUE THREAD

**Issue by arsalan993** [facebook/folly#766]
`-- Found libevent: /usr/lib/x86_64-linux-gnu/libevent.so
-- Setting FOLLY_USE_SYMBOLIZER: ON
CMake Error at CMakeLists.txt:104 (list):
  list sub-command REMOVE_ITEM requires list to be present.

CMake Error at CMakeLists.txt:109 (list):
  list sub-command REMOVE_ITEM requires list to be present.

-- Configuring incomplete, errors occurred!
See also "/home/test/Downloads/folly/_build/CMakeFiles/CMakeOutput.log".
See also "/home/test/Downloads/folly/_build/CMakeFiles/CMakeError.log".`

**Comment by ecarew** [comment]
I got simmilar errors in the cmake stage. Note, that I'm building folly because I also failed to build the proxygen project, and am trying to build its dependencies separately. What follows is the output from the cmake run:

`evxx@evxx:~/Projects/folly/folly/_build$ cmake configure ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:6 (apply_folly_compile_options_to_target):
  Unknown CMake command "apply_folly_compile_options_to_target".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.5)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/evxx/Projects/folly/folly/_build/CMakeFiles/CMakeOutput.log".
`

**Comment by JoeLoser** [comment]
Mind sharing some more info such as which OS and version of CMake?

**Comment by ineslyl** [comment]
Hello, i have the same problem. The version of CMake is 3.11.0-rc2. 

[root@localhost _build]# cmake configure ..
-- Boost version: 1.53.0
-- Found the following Boost libraries:
--   context
--   chrono
--   date_time
--   filesystem
--   program_options
--   regex
--   system
--   thread
--   atomic
-- Found double-conversion: /usr/local/lib/libdouble-conversion.so
-- Found gflags from package config
-- Found libevent: /usr/lib64/libevent.so
-- Found LZ4: /usr/lib64/liblz4.so
-- Found Zstd: /usr/lib64/libzstd.so
-- Could NOT find LIBIBERTY (missing: LIBIBERTY_INCLUDE_DIR)
-- Setting FOLLY_USE_SYMBOLIZER: ON
CMake Error at CMakeLists.txt:104 (list):
  list sub-command REMOVE_ITEM requires list to be present.


CMake Error at CMakeLists.txt:109 (list):
  list sub-command REMOVE_ITEM requires list to be present.


-- Configuring incomplete, errors occurred!
See also "/home/liyilun/tools/folly/CMakeFiles/CMakeOutput.log".
See also "/home/liyilun/tools/folly/CMakeFiles/CMakeError.log".


There are some solutions maybe?

**Comment by shixiao** [comment]
@ineslyl , make sure you install all the dependencies on Ubuntu via apt-get (https://github.com/facebook/folly#ubuntu-1604-lts)? After that, try removing `CMakeCache.txt`, and running `cd _build && cmake configure ..`

The line in your log `-- Could NOT find LIBIBERTY (missing: LIBIBERTY_INCLUDE_DIR)` suggests that you are missing `libiberty`.

**Comment by zhshw** [comment]
Folly need to support ubuntu17, too many compiled errors, not need useless replies！
follw this link  [](https://github.com/facebook/folly#ubuntu-1604-lts)  the same cannot complied pass！

**Comment by martinkocicka** [comment]
I figured out what the problem was in my case. Paths in (h)files list are absolute, and I had folly in /home/martin/build/folly-2018.04.09.00/, which means the pattern /build/ matched all my files, and removed everything from the list, hence the empty list error. Changing the pattern to my absolute path fixed it.

**Comment by BalajiB197** [comment]
I am facing the same issue,  in recent release (version-1.1).
can anybody guide me in fixing this issue?
Thanks

**Comment by mxcl** [comment]
the fix for me was to stop untarring with `--strip-components=1`. Which my build tooling was doing for me.
