### ISSUE TITLE
[Macports configure failed][Openssl][MacOS] Configure failed due to can't find openssl/ssl.h

### ISSUE THREAD

**Issue by oscarriddle** [facebook/folly#814]
Hi,

I tried to install folly by macports. My OS is OSX High Sierra 10.13.3.
When I proceeded to the step `./configure CPPFLAGS="-I/opt/local/include" LDFLAGS="-L/opt/local/lib"`
I got the below fail:
```
checking for pkg-config... /usr/local/bin/pkg-config
checking for openssl/ssl.h in /usr/local/Cellar/openssl/1.0.2o_1/include/... no
checking for openssl/ssl.h in /opt/local/bin/openssl... no
checking for openssl/ssl.h in /usr/lib/openssl... no
checking for openssl/ssl.h in /usr/openssl... no
checking for openssl/ssl.h in /usr/pkg... no
checking for openssl/ssl.h in /usr/local... no
checking for openssl/ssl.h in /usr... no
checking whether compiling and linking against OpenSSL works... no
configure: error: "Error: libssl required"
```

Note that the path "/usr/local/Cellar/openssl/1.0.2o_1/include/" is where I brew installed the openssl in, and I located the openssl/ssl.h can indeed be found under this path. So I just modified the configure file to add this location:

```
            # no such luck; use some default ssldirs
            if ! $found; then
                ssldirs="/usr/local/Cellar/openssl/1.0.2o_1/include /opt/local/bin/openssl /usr/lib/openssl /usr/openssl /usr/pkg /usr/local /usr"
            fi
```

When I try to confirm the installation of openssl, I got below:
```
giga:user$ which openssl
/opt/local/bin/openssl
giga:user$ openssl version
OpenSSL 1.0.2o  27 Mar 2018
```

Has anyone encountered the same problem? 
Any idea will be welcome.

Thanks,

**Comment by JoeLoser** [comment]
I can't quite help you with this specific MacPorts issue, but, is there a particular reason why you cannot use CMake? I understand the top-level `README.md` wants you to use autotools, but the CMake is stable in my opinion. As of the last month or so, it should build just fine with Clang 6 and CMake. I have not tried with Apple Clang, however.

When building on Mac, you'll want to use `CMAKE_INCLUDE_PATH` and `CMAKE_LIBRARY_PATH` to point at the OpenSSL install root from Homebrew. Then they will pick these up at CMake's `configure` time rather than the "broken" OS-installed package of OpenSSL.

**Comment by ugogiordano87** [comment]
With the "which openssl" command you just find the location of the openssl binary file, while the folly configuration requires the openssl library and include files. 

To workaround this issue type `ls -l /usr/local/opt/openssl` to find if any link to the openssl tool exists. 
Then, just specify the `--with-openssl` option of the folly configure as following `--with-openssl=/usr/local/opt/openssl`.

That said, you should install folly with the Homebrew formula by simply running the `folly/build/bootstrap-osx-homebrew.sh` script .
