### ISSUE TITLE
Linking error while using AtomicHashMap

### ISSUE THREAD

**Issue by ugiordan** [facebook/folly#821]
When using the AtomicHashMap.h file I got the following linking error:

> "folly::threadlocal_detail::StaticMetaBase::getThreadEntryList()",
> referenced from: folly::threadlocal_detail::StaticMeta<unsigned long long, folly::AccessModeStrict>::getThreadEntrySlow()

**Comment by yfeldblum** [comment]
The function is defined in `folly/detail/ThreadLocalDetail.cpp`. Are you linking with that?

**Comment by ugogiordano87** [comment]
I’m linking both folly and follyinit libraries in my cmake file, so yes the file you’re mentioning should be already linked.

**Comment by ugogiordano87** [comment]
After reading the `ThreadLocalDetail.h` and `ThreadLocalDetail.cpp` I figured out what is the problem. 

Basically, the `getThreadEntryList()` is declared within the `StaticMetaBase` struct (and implemented in the .cpp file) which is then extended by the **template** `StaticMeta` struct. 

When the `getThreadEntryList()` is called within the `getThreadEntrySlow()` of the  **template** `StaticMeta` struct the compiler needs to have access to the implementation of the function to instantiate it with the template argument. 
However, the compiler can't access to the implementation of the `getThreadEntryList()` function (since it is in the .cpp file) and consequently it wouldn't be able to instantiate the template struct.

So, a possible workaround to this problem is to move the implementation of the `getThreadEntryList()` function from the .cpp file to the header file. 

I think that this should be fixed!
