### ISSUE TITLE
Can I use fixed size MPMCQueue in a shared memory? (Boost)

### ISSUE THREAD

**Issue by yangfanLxy** [facebook/folly#959]
I think I can replace `raw pointer` with boost's `offset_ptr`, replace origin `new` with boost's `managed_shared_memory` allocator.
Is that possible? 
thanks

**Comment by nbronson** [comment]
This could be made to work, but it doesn't at the moment. One missing piece is that folly::detail::Futex would need to be extended with a template parameter that caused it to not pass FUTEX_PRIVATE_FLAG to the futex() syscall, and that template parameter would need to be plumbed through the MPMCQueue type. For robust usage you would probably also need to figure out a way to recover if a process that was blocked trying to read or write the queue was killed. At the moment that would cause the queue to become unusable, since there is no support for recovery after a partial failure.

**Comment by yfeldblum** [comment]
Closing because the question, as asked, has been answered.

I doubt that FB has a strict plan to bake shared-memory support into this data structure, although it may happen in the future if it becomes necessary within FB or if someone volunteers to do it.
